-- Run this in the Supabase SQL Editor

create table users (
  id bigint generated by default as identity primary key,
  name text,
  email text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert some dummy data
insert into users (name, email) values
  ('Alice Johnson', 'alice@example.com'),
  ('Bob Smith', 'bob@test.com'),
  ('Charlie Brown', 'charlie@demo.org');
