-- ─────────────────────────────────────────────────────────────────────────────
-- Original flight_data table (legacy)
-- ─────────────────────────────────────────────────────────────────────────────

-- Run this in the Supabase SQL Editor

create table flight_data (
  id bigint generated by default as identity primary key,
  flight_number int,
  drone_type text,
  flight_time timestamp with time zone,
  power_watts float,
  current_amps float,
  batteryTemp float,
  ambiantTemp float,
  airSpeed float,
  windDirection_rad float,
  windSpeed_mps float,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert some dummy data
insert into flight_data 
(flight_number, drone_type, flight_time, power_watts, current_amps, batteryTemp, ambiantTemp, airSpeed, windDirection_rad, windSpeed_mps) 
values
(101, 'DroneA', '2026-02-20 10:00:00+00', 450.5, 18.2, 35.4, 22.1, 12.5, 1.57, 5.2),
(101, 'DroneA', '2026-02-20 10:05:00+00', 470.2, 19.0, 36.0, 22.5, 13.0, 1.60, 5.5),
(102, 'DroneB', '2026-02-20 11:00:00+00', 520.8, 21.5, 40.2, 25.3, 15.8, 0.78, 3.8),
(102, 'DroneB', '2026-02-20 11:05:00+00', 510.0, 20.9, 39.7, 25.0, 16.1, 0.82, 4.1),
(103, 'DroneC', '2026-02-20 12:00:00+00', 390.3, 15.7, 33.2, 20.4, 10.2, 2.10, 6.0),
(103, 'DroneC', '2026-02-20 12:05:00+00', 405.6, 16.3, 34.1, 20.9, 10.8, 2.05, 6.3);
-- Enable Row Level Security (RLS)
alter table flight_data enable row level security;

-- Create a policy to allow public read access
create policy "Allow public read access"
  on flight_data
  for select
  to anon
  using (true);

-- Create a policy to allow public insert access
create policy "Allow public insert access"
  on flight_data
  for insert
  to anon
  with check (true);

-- ─────────────────────────────────────────────────────────────────────────────
-- NEW: flight_telemetry table — matches the XLSX telemetry file columns
-- Run this block in the Supabase SQL Editor
-- ─────────────────────────────────────────────────────────────────────────────

create table if not exists flight_telemetry (
  id                      bigint generated by default as identity primary key,
  uploaded_at             timestamp with time zone default timezone('utc'::text, now()) not null,

  -- Time
  min_sec                 text,
  rtc_utc                 timestamp with time zone,
  gps_utc                 timestamp with time zone,
  gps_synced              boolean,

  -- Battery
  battery_temp_c          float,
  battery_current_a       float,
  battery_voltage_v       float,
  battery_power_w         float,

  -- Power Module
  pm_voltage_v            float,
  pm_current_a            float,
  pm_power_w              float,
  pm_consumed_mah         float,
  pm_remaining_pct        float,

  -- IMU Orientation
  imu_roll_rads           float,
  imu_pitch_rads          float,
  imu_yaw_rads            float,
  imu_roll_speed_rads_s   float,
  imu_pitch_speed_rads_s  float,
  imu_yaw_speed_rads_s    float,

  -- IMU Accelerometer
  imu_x_acc_cm_s2         float,
  imu_y_acc_cm_s2         float,
  imu_z_acc_cm_s2         float,

  -- IMU Gyro
  imu_x_gyro_rad_s        float,
  imu_y_gyro_rad_s        float,
  imu_z_gyro_rad_s        float,

  -- IMU Magnetometer
  imu_x_mag_rad_s         float,
  imu_y_mag_rad_s         float,
  imu_z_mag_rad_s         float,

  -- Raw GPS
  rawgps_lat              float,
  rawgps_lon              float,
  rawgps_alt_mm           float,
  rawgps_vel_m_s          float,
  rawgps_sats             int,

  -- Fused GPS
  fusedgps_lat            float,
  fusedgps_lon            float,
  fusedgps_alt_msl_mm     float,
  fusedgps_alt_rel_mm     float,
  fusedgps_velx_cm_s      float,
  fusedgps_vely_cm_s      float,
  fusedgps_velz_cm_s      float,
  fusedgps_head           float
);

-- Enable RLS
alter table flight_telemetry enable row level security;

create policy "Allow public read access on telemetry"
  on flight_telemetry for select to anon using (true);

create policy "Allow public insert access on telemetry"
  on flight_telemetry for insert to anon with check (true);
