-- Run this in the Supabase SQL Editor

create table flight_data (
  id bigint generated by default as identity primary key,
  flight_number int,
  drone_type text,
  current_time timestamp,
  power_watts float,
  current_amps float,
  batteryTemp float,
  ambiantTemp float,
  airSpeed float,
  windDirection_rad float,
  windSpeed_mps float,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert some dummy data
insert into flight_data 
(flight_number, drone_type, current_time, power_watts, current_amps, batteryTemp, ambiantTemp, airSpeed, windDirection_rad, windSpeed_mps) 
values
(101, 'DroneA', '2026-02-20 10:00:00', 450.5, 18.2, 35.4, 22.1, 12.5, 1.57, 5.2),
(101, 'DroneA', '2026-02-20 10:05:00', 470.2, 19.0, 36.0, 22.5, 13.0, 1.60, 5.5),
(102, 'DroneB', '2026-02-20 11:00:00', 520.8, 21.5, 40.2, 25.3, 15.8, 0.78, 3.8),
(102, 'DroneB', '2026-02-20 11:05:00', 510.0, 20.9, 39.7, 25.0, 16.1, 0.82, 4.1),
(103, 'DroneC', '2026-02-20 12:00:00', 390.3, 15.7, 33.2, 20.4, 10.2, 2.10, 6.0),
(103, 'DroneC', '2026-02-20 12:05:00', 405.6, 16.3, 34.1, 20.9, 10.8, 2.05, 6.3);
-- Enable Row Level Security (RLS)
alter table flight_data enable row level security;

-- Create a policy to allow public read access
create policy "Allow public read access"
  on flight_data
  for select
  to anon
  using (true);

-- Create a policy to allow public insert access
create policy "Allow public insert access"
  on flight_data
  for insert
  to anon
  with check (true);
